//console.log(tab);
//await grabTheModal(tab);
//await browser.close();
//console.log(modalContents);
// let input = await tab.$$('.ee-Ii-Zb-Uj');
// console.log(input);
//await tab.waitForSelector('.a-b-c.d-u.d-u-R', {visible:true});
//console.log("jsdhbc");
//await tab.click(".a-b-c.d-u.d-u-R");
//await tab.waitForTimeout(3000);
//await tab.waitForSelector('.ee-Ii-Zb-Uj', {visible:true});
//await input.click();
//let input = await tab.$$('img[alt="Add a photo"]');
//await input.click();
//console.log(input);
// await tab.on('.picker.modal-dialog.picker-dialog');
// const input = await tab.$('.a-b-c.d-u.d-u-R');
// console.log(input);
//await input.uploadFile(`${picPathName}`);